package com.dingapp.biz.util;

public class BizConstants {
	public static String ctorPriceInfo() {
		StringBuilder sb = new StringBuilder();
		sb.append("<html><meta http-equiv='content-type' content='text/html; charset=UTF-8' />");
		sb.append("<body >");
		sb.append("<p style=\"text-indent:2em;font-size:2em;\">佛山保利水城比邻洗衣店洗衣定价表</p>");
		sb.append("<table border=1 style='font-size:2em;border-collapse: collapse;'>");
		sb.append("<tr><th >类别</th><th>项目</th><th>干洗</th><th>湿洗</th></tr>");
		sb.append("<tr>");
		sb.append("<td rowspan='15'>上衣类</td>");
		sb.append("<td >毛呢大衣(长/短）</td>");
		sb.append("<td >65.00/55.00</td>");
		sb.append("<td >50.00/40.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td >西服(一套)</td><td >58.00</td><td >-</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td >普通外套</td><td >35.00</td><td >-</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td >棉服外套</td><td >45.00</td><td >35.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td >T恤（夏/冬）</td><td >20.00/25.00</td><td >18.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td >毛衣</td><td >30.00</td><td >25.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td >Dress Shirt</td><td >30.00</td><td >25.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td >衬衫</td><td >22.00</td><td >20.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td >羽绒服(长/短）</td><td >-</td><td >65.00/52.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td >羽绒背心</td><td >-</td><td >40.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td >运动休闲衣/卫衣</td><td >-</td><td >28.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>运动套装</td><td>-</td><td>48.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>西装上衣</td><td>38.00</td><td>-</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>夹克</td><td>30.00</td><td>25.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>风衣</td><td>48.00</td><td>40.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td rowspan='7'>下装>类</td>");
		sb.append("<td>Jeans</td><td>-</td><td>25.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>长裙</td><td>33.00</td><td>28.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>短裙(牛仔裙、西裙）</td><td>25.00</td><td>20.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>连衣裙</td><td>38.00</td><td>32.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>百折裙</td><td>48.00</td><td>40</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>运动/休闲裤</td><td>－</td><td>20.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>西裤</td><td>28.00</td><td>－</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td rowspan='8'>床上用品类</td>");
		sb.append("<td>羽绒被</td><td>-</td><td>110.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>床上四件套</td><td>－</td><td>88.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>被套</td><td>－</td><td>45</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>床单</td><td>－</td><td>35</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>枕头套</td><td>－</td><td>15.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>毛毯</td><td>－</td><td>78.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>沙发套(2-3人)</td><td>－</td><td>48.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>枕芯</td><td>－</td><td>35.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td rowspan='8'>小件类</td>");
		sb.append("<td>领带</td><td>15.00</td><td>－</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>围巾</td><td>22.00</td><td>－</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>袜子/对</td><td>－</td><td>12.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>手套/对</td><td>－</td><td>15.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>短裤</td><td>－</td><td>15.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>内裤</td><td>－</td><td>12.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>吊带/汗衫</td><td>－</td><td>16</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>手帕</td><td>－</td><td>10.00</td>");
		sb.append("</tr>");
		sb.append("<tr><td></td><td colspan='4'>");
		sb.append("说明：对于洗衣>单上没有显示物品名称，采取议价形式进行，");
		sb.append("比如：背包送洗采取手工水洗法收费标准按30元/个。单独熨烫按照原价的75%收费。</td></tr>");
		sb.append("</table>");
		sb.append("<p style=\"text-indent:2em;font-size:2em;border-collapse:collapse;\">");
		sb.append("比邻洗衣门店价格（册子）</p>");
		sb.append("<table border=1 style='font-size:2em'>");
		sb.append("<tr><th>类别</th><th colspan='2'>项目</th><th>干洗</th><th>湿洗</th></tr>");
		sb.append("<tr>");
		sb.append("<td rowspan='5'>常规上衣</td>");
		sb.append("<td>－</td><td>马甲</td><td>18</td><td>-</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>毛衣连衣裙</td><td>40</td><td>-</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>连衣裤（背带裤）</td><td>30</td><td>-</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>牛仔衫<br/>/牛仔衬衣</td><td>28</td><td>35.00</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>牛仔外套</td><td>－</td><td>35</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td rowspan='5'>非常规衣物</td>");
		sb.append("<td>－</td><td>军装上衣</td><td>38</td><td>-</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>军裤</td><td>28</td><td>-</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>军装套装</td><td>55</td><td>-</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>军用大衣（保安式长棉服）</td><td>－</td><td>60</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>厨衣，医用白大褂</td><td>38</td><td>－</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td rowspan='9'>贴身、家居衣物</td>");
		sb.append("<td>－</td><td>睡衣/家居服（上衣）</td><td>-</td><td>22</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>睡裤/家居裤</td><td>-</td><td>20</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>普通睡衣裤/带绒家居服（整套）</td><td>-</td><td>38</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>浴袍</td><td>－</td><td>30</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>秋衣/保暖内衣</td><td>-</td><td>18</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>-</td><td>秋裤/保暖内裤</td><td>－</td><td>15</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>-</td><td>秋衣裤/保暖内衣裤（整套）</td><td>-</td><td>30</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>-</td><td>毛线裤</td><td>18</td><td>25</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>-</td><td>内衣（女士文胸）</td><td>-</td><td>15</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td rowspan='6'>演出、婚礼类</td>");
		sb.append("<td>－</td><td>婚纱</td><td>128-300</td><td>－</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>旗袍</td><td>45-90</td><td>－</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>燕尾服</td><td>50/65</td><td>－</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>女士晚礼服（长）</td><td>100－160</td><td>－</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>女士晚礼服（短）</td><td>65-100</td><td>－</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>-</td><td>西装背心</td><td>25</td><td>－</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td rowspan='4'>床上用品类</td>");
		sb.append("<td>－</td><td>床罩</td><td>-</td><td>40</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>蚊帐</td><td>－</td><td>28</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>踏花被</td><td>－</td><td>50</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>毛巾被</td><td>－</td><td>35</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td rowspan='10'>家居生活用品（大件）</td>");
		sb.append("<td>－</td><td>窗帘</td><td>-</td><td>8元/㎡</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>窗纱</td><td>－</td><td>6元/㎡</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>餐桌布（整块）</td><td>－</td><td>38</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>西式装饰桌布（条）</td><td>－</td><td>26</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>-</td><td>椅套/个</td><td>－</td><td>22</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>沙发垫/人</td><td>－</td><td>26</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>沙发套/人</td><td>－</td><td>25</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>汽车坐垫（单个/全套5个）</td><td>－</td><td>22/100</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>公仔（可脱卸）</td><td>－</td><td>25-48</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>背包（根据大小，用途）</td><td>－</td><td>28-45</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td rowspan='4'>家居生活用品（小件）</td>");
		sb.append("<td>-</td><td>围巾</td><td>20</td><td>－</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>布帽子/顶</td><td>15</td><td>－</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>浴巾</td><td>－</td><td>20</td>");
		sb.append("</tr>");
		sb.append("<tr>");
		sb.append("<td>－</td><td>普通毛巾</td><td>－</td><td>15</td>");
		sb.append("</tr>");
		sb.append("</table>");
		sb.append("</div>");
		sb.append("</div>");
		sb.append("</div>");
		sb.append("<br/>");
		sb.append("<br/>");
		sb.append("</body></html>");
		return sb.toString();
	}
}
